// DO NOT EDIT, generated by goctl
package types

type CheckReq struct {
	Action string `form:"action"`
}

type CheckResp struct {
	Msg  string   `json:"msg" desc:"业务提示"`
	Code int      `json:"code"  desc:"业务码"`
	Meta MetaData `json:"meta,optional=1" desc:"数据元"`
}

type ExecData struct {
	Key   string      `json:"key" desc:"对象键名"`
	Value interface{} `json:"value" desc:"数据"`
}

type ExecReq struct {
	Action     string   `json:"action" from:"action" desc:"命令"`
	Params     []string `json:"params" from:"params" desc:"参数"`
	ReturnBody string   `json:"returnBody,optional" from:"returnBody" desc:"返回结果体"`
	Input      string   `json:"input" from:"input" desc:"输入文件"`
}

type ExecResp struct {
	Msg   string     `json:"msg"  desc:"业务提示"`
	Code  int        `json:"code" desc:"业务码"`
	Error RespError  `json:"error,optional" desc:"错误信息对象"`
	Data  []ExecData `json:"data" desc:"数据对象数组"`
	Meta  MetaData   `json:"meta,optional" desc:"扩展元数据"`
}

type MetaData struct {
	Values []ExecData `json:"values" desc:"数据元数组"`
}

type RespError struct {
	Errno  int    `json:"errno" desc:"错误码"`
	Errmsg string `json:"errmsg" desc:"错误提示"`
}
