// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

package checker

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	Any struct {
		TypeUrl string `json:"type_url,omitempty"`
		Value   []byte `json:"value,omitempty"`
	}

	Entry struct {
		Key   string `json:"key,omitempty"`
		Value *Any   `json:"value,omitempty"`
	}

	Error struct {
		Errmsg string `json:"errmsg,omitempty"`
		Errno  int32  `json:"errno,omitempty"`
	}

	MetaData struct {
		Data []*Entry `json:"data,omitempty"`
	}

	Request struct {
		Action string `json:"action,omitempty"`
	}

	Response struct {
		Msg   string        `json:"msg,omitempty"`
		Code  Response_Code `json:"code,omitempty"`
		Data  []*Entry      `json:"data,omitempty"`
		Error *Error        `json:"error,omitempty"`
		Meta  *MetaData     `json:"meta,omitempty"`
	}
)
