// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	"github.com/weblfe/ffmpeg-service/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/exec",
			Handler: execHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/check",
			Handler: checkHandler(serverCtx),
		},
	})
}
