// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.3
// source: check.proto

package check

import (
		context "context"
		"encoding/json"
		proto "github.com/golang/protobuf/proto"
		grpc "google.golang.org/grpc"
		codes "google.golang.org/grpc/codes"
		status "google.golang.org/grpc/status"
		protoreflect "google.golang.org/protobuf/reflect/protoreflect"
		protoimpl "google.golang.org/protobuf/runtime/protoimpl"
		reflect "reflect"
		sync "sync"
)

const (
		// Verify that this generated code is sufficiently up-to-date.
		_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
		// Verify that runtime/protoimpl is sufficiently up-to-date.
		_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Response_Code int32

const (
		Response_SUCCESS Response_Code = 0
		Response_WARNING Response_Code = 3000
		Response_FAILED  Response_Code = 4000
		Response_EMPTY   Response_Code = 4040
		Response_ERROR   Response_Code = 5000
)

// Enum value maps for Response_Code.
var (
		Response_Code_name = map[int32]string{
				0:    "SUCCESS",
				3000: "WARNING",
				4000: "FAILED",
				4040: "EMPTY",
				5000: "ERROR",
		}
		Response_Code_value = map[string]int32{
				"SUCCESS": 0,
				"WARNING": 3000,
				"FAILED":  4000,
				"EMPTY":   4040,
				"ERROR":   5000,
		}
)

func (x Response_Code) Enum() *Response_Code {
		p := new(Response_Code)
		*p = x
		return p
}

func (x Response_Code) String() string {
		return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Code) Descriptor() protoreflect.EnumDescriptor {
		return file_check_proto_enumTypes[0].Descriptor()
}

func (Response_Code) Type() protoreflect.EnumType {
		return &file_check_proto_enumTypes[0]
}

func (x Response_Code) Number() protoreflect.EnumNumber {
		return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Code.Descriptor instead.
func (Response_Code) EnumDescriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{4, 0}
}

type MetaData struct {
		state         protoimpl.MessageState
		sizeCache     protoimpl.SizeCache
		unknownFields protoimpl.UnknownFields

		Data []*Entry `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *MetaData) Reset() {
		*x = MetaData{}
		if protoimpl.UnsafeEnabled {
				mi := &file_check_proto_msgTypes[0]
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				ms.StoreMessageInfo(mi)
		}
}

func (x *MetaData) String() string {
		return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
		mi := &file_check_proto_msgTypes[0]
		if protoimpl.UnsafeEnabled && x != nil {
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				if ms.LoadMessageInfo() == nil {
						ms.StoreMessageInfo(mi)
				}
				return ms
		}
		return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{0}
}

func (x *MetaData) GetData() []*Entry {
		if x != nil {
				return x.Data
		}
		return nil
}

type Entry struct {
		state         protoimpl.MessageState
		sizeCache     protoimpl.SizeCache
		unknownFields protoimpl.UnknownFields

		Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
		Value *Any   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Entry) Reset() {
		*x = Entry{}
		if protoimpl.UnsafeEnabled {
				mi := &file_check_proto_msgTypes[1]
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				ms.StoreMessageInfo(mi)
		}
}

func (x *Entry) String() string {
		return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
		mi := &file_check_proto_msgTypes[1]
		if protoimpl.UnsafeEnabled && x != nil {
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				if ms.LoadMessageInfo() == nil {
						ms.StoreMessageInfo(mi)
				}
				return ms
		}
		return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetKey() string {
		if x != nil {
				return x.Key
		}
		return ""
}

func (x *Entry) GetValue() *Any {
		if x != nil {
				return x.Value
		}
		return nil
}

type Any struct {
		state         protoimpl.MessageState
		sizeCache     protoimpl.SizeCache
		unknownFields protoimpl.UnknownFields

		TypeUrl string `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
		Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Any) Reset() {
		*x = Any{}
		if protoimpl.UnsafeEnabled {
				mi := &file_check_proto_msgTypes[2]
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				ms.StoreMessageInfo(mi)
		}
}

func (x *Any) String() string {
		return protoimpl.X.MessageStringOf(x)
}

func (*Any) ProtoMessage() {}

func (x *Any) ProtoReflect() protoreflect.Message {
		mi := &file_check_proto_msgTypes[2]
		if protoimpl.UnsafeEnabled && x != nil {
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				if ms.LoadMessageInfo() == nil {
						ms.StoreMessageInfo(mi)
				}
				return ms
		}
		return mi.MessageOf(x)
}

// Deprecated: Use Any.ProtoReflect.Descriptor instead.
func (*Any) Descriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{2}
}

func (x *Any) GetTypeUrl() string {
		if x != nil {
				return x.TypeUrl
		}
		return ""
}

func (x *Any) GetValue() []byte {
		if x != nil {
				return x.Value
		}
		return nil
}

func (x *Any) GetVal() interface{} {
		if x != nil && x.Value != nil {
				var v = new(interface{})
				if err := json.Unmarshal(x.Value, v); err == nil {
						return v
				}
		}
		return nil
}

func (x *Any) GetData(data interface{}) error {
		if x != nil && x.Value != nil {
				return json.Unmarshal(x.Value, data)
		}
		return nil
}

type Request struct {
		state         protoimpl.MessageState
		sizeCache     protoimpl.SizeCache
		unknownFields protoimpl.UnknownFields

		Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *Request) Reset() {
		*x = Request{}
		if protoimpl.UnsafeEnabled {
				mi := &file_check_proto_msgTypes[3]
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				ms.StoreMessageInfo(mi)
		}
}

func (x *Request) String() string {
		return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
		mi := &file_check_proto_msgTypes[3]
		if protoimpl.UnsafeEnabled && x != nil {
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				if ms.LoadMessageInfo() == nil {
						ms.StoreMessageInfo(mi)
				}
				return ms
		}
		return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetAction() string {
		if x != nil {
				return x.Action
		}
		return ""
}

type Response struct {
		state         protoimpl.MessageState
		sizeCache     protoimpl.SizeCache
		unknownFields protoimpl.UnknownFields

		Msg   string        `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
		Code  Response_Code `protobuf:"varint,2,opt,name=code,proto3,enum=check.Response_Code" json:"code,omitempty"`
		Data  []*Entry      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
		Error *Error        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
		Meta  *MetaData     `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *Response) Reset() {
		*x = Response{}
		if protoimpl.UnsafeEnabled {
				mi := &file_check_proto_msgTypes[4]
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				ms.StoreMessageInfo(mi)
		}
}

func (x *Response) String() string {
		return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
		mi := &file_check_proto_msgTypes[4]
		if protoimpl.UnsafeEnabled && x != nil {
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				if ms.LoadMessageInfo() == nil {
						ms.StoreMessageInfo(mi)
				}
				return ms
		}
		return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetMsg() string {
		if x != nil {
				return x.Msg
		}
		return ""
}

func (x *Response) GetCode() Response_Code {
		if x != nil {
				return x.Code
		}
		return Response_SUCCESS
}

func (x *Response) GetData() []*Entry {
		if x != nil {
				return x.Data
		}
		return nil
}

func (x *Response) GetError() *Error {
		if x != nil {
				return x.Error
		}
		return nil
}

func (x *Response) GetMeta() *MetaData {
		if x != nil {
				return x.Meta
		}
		return nil
}

type Error struct {
		state         protoimpl.MessageState
		sizeCache     protoimpl.SizeCache
		unknownFields protoimpl.UnknownFields

		Errmsg string `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
		Errno  int32  `protobuf:"varint,2,opt,name=errno,proto3" json:"errno,omitempty"`
}

func (x *Error) Reset() {
		*x = Error{}
		if protoimpl.UnsafeEnabled {
				mi := &file_check_proto_msgTypes[5]
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				ms.StoreMessageInfo(mi)
		}
}

func (x *Error) String() string {
		return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
		mi := &file_check_proto_msgTypes[5]
		if protoimpl.UnsafeEnabled && x != nil {
				ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
				if ms.LoadMessageInfo() == nil {
						ms.StoreMessageInfo(mi)
				}
				return ms
		}
		return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
		return file_check_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetErrmsg() string {
		if x != nil {
				return x.Errmsg
		}
		return ""
}

func (x *Error) GetErrno() int32 {
		if x != nil {
				return x.Errno
		}
		return 0
}

var File_check_proto protoreflect.FileDescriptor

var file_check_proto_rawDesc = []byte{
		0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
		0x68, 0x65, 0x63, 0x6b, 0x22, 0x2c, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
		0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
		0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61,
		0x74, 0x61, 0x22, 0x3b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
		0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a,
		0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63,
		0x68, 0x65, 0x63, 0x6b, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
		0x36, 0x0a, 0x03, 0x41, 0x6e, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x75,
		0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x79, 0x70, 0x65, 0x55, 0x72,
		0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
		0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
		0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
		0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xf9, 0x01, 0x0a, 0x08, 0x52,
		0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
		0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x64,
		0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e,
		0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
		0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
		0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
		0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04,
		0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x45, 0x72, 0x72,
		0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x65, 0x74,
		0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e,
		0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x46,
		0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
		0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0xb8,
		0x17, 0x12, 0x0b, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0xa0, 0x1f, 0x12, 0x0a,
		0x0a, 0x05, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0xc8, 0x1f, 0x12, 0x0a, 0x0a, 0x05, 0x45, 0x52,
		0x52, 0x4f, 0x52, 0x10, 0x88, 0x27, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
		0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
		0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f,
		0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x32, 0x33, 0x0a,
		0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63,
		0x6b, 0x12, 0x0e, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
		0x74, 0x1a, 0x0f, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
		0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
		file_check_proto_rawDescOnce sync.Once
		file_check_proto_rawDescData = file_check_proto_rawDesc
)

func file_check_proto_rawDescGZIP() []byte {
		file_check_proto_rawDescOnce.Do(func() {
				file_check_proto_rawDescData = protoimpl.X.CompressGZIP(file_check_proto_rawDescData)
		})
		return file_check_proto_rawDescData
}

var file_check_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_check_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_check_proto_goTypes = []interface{}{
		(Response_Code)(0), // 0: check.Response.Code
		(*MetaData)(nil),   // 1: check.MetaData
		(*Entry)(nil),      // 2: check.Entry
		(*Any)(nil),        // 3: check.Any
		(*Request)(nil),    // 4: check.Request
		(*Response)(nil),   // 5: check.Response
		(*Error)(nil),      // 6: check.Error
}
var file_check_proto_depIdxs = []int32{
		2, // 0: check.MetaData.data:type_name -> check.Entry
		3, // 1: check.Entry.value:type_name -> check.Any
		0, // 2: check.Response.code:type_name -> check.Response.Code
		2, // 3: check.Response.data:type_name -> check.Entry
		6, // 4: check.Response.error:type_name -> check.Error
		1, // 5: check.Response.meta:type_name -> check.MetaData
		4, // 6: check.Checker.check:input_type -> check.Request
		5, // 7: check.Checker.check:output_type -> check.Response
		7, // [7:8] is the sub-list for method output_type
		6, // [6:7] is the sub-list for method input_type
		6, // [6:6] is the sub-list for extension type_name
		6, // [6:6] is the sub-list for extension extendee
		0, // [0:6] is the sub-list for field type_name
}

func init() { file_check_proto_init() }
func file_check_proto_init() {
		if File_check_proto != nil {
				return
		}
		if !protoimpl.UnsafeEnabled {
				file_check_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
						switch v := v.(*MetaData); i {
						case 0:
								return &v.state
						case 1:
								return &v.sizeCache
						case 2:
								return &v.unknownFields
						default:
								return nil
						}
				}
				file_check_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
						switch v := v.(*Entry); i {
						case 0:
								return &v.state
						case 1:
								return &v.sizeCache
						case 2:
								return &v.unknownFields
						default:
								return nil
						}
				}
				file_check_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
						switch v := v.(*Any); i {
						case 0:
								return &v.state
						case 1:
								return &v.sizeCache
						case 2:
								return &v.unknownFields
						default:
								return nil
						}
				}
				file_check_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
						switch v := v.(*Request); i {
						case 0:
								return &v.state
						case 1:
								return &v.sizeCache
						case 2:
								return &v.unknownFields
						default:
								return nil
						}
				}
				file_check_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
						switch v := v.(*Response); i {
						case 0:
								return &v.state
						case 1:
								return &v.sizeCache
						case 2:
								return &v.unknownFields
						default:
								return nil
						}
				}
				file_check_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
						switch v := v.(*Error); i {
						case 0:
								return &v.state
						case 1:
								return &v.sizeCache
						case 2:
								return &v.unknownFields
						default:
								return nil
						}
				}
		}
		type x struct{}
		out := protoimpl.TypeBuilder{
				File: protoimpl.DescBuilder{
						GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
						RawDescriptor: file_check_proto_rawDesc,
						NumEnums:      1,
						NumMessages:   6,
						NumExtensions: 0,
						NumServices:   1,
				},
				GoTypes:           file_check_proto_goTypes,
				DependencyIndexes: file_check_proto_depIdxs,
				EnumInfos:         file_check_proto_enumTypes,
				MessageInfos:      file_check_proto_msgTypes,
		}.Build()
		File_check_proto = out.File
		file_check_proto_rawDesc = nil
		file_check_proto_goTypes = nil
		file_check_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CheckerClient is the client API for Checker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckerClient interface {
		Check(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type checkerClient struct {
		cc grpc.ClientConnInterface
}

func NewCheckerClient(cc grpc.ClientConnInterface) CheckerClient {
		return &checkerClient{cc}
}

func (c *checkerClient) Check(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
		out := new(Response)
		err := c.cc.Invoke(ctx, "/check.Checker/check", in, out, opts...)
		if err != nil {
				return nil, err
		}
		return out, nil
}

// CheckerServer is the server API for Checker service.
type CheckerServer interface {
		Check(context.Context, *Request) (*Response, error)
}

// UnimplementedCheckerServer can be embedded to have forward compatible implementations.
type UnimplementedCheckerServer struct {
}

func (*UnimplementedCheckerServer) Check(context.Context, *Request) (*Response, error) {
		return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterCheckerServer(s *grpc.Server, srv CheckerServer) {
		s.RegisterService(&_Checker_serviceDesc, srv)
}

func _Checker_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
		in := new(Request)
		if err := dec(in); err != nil {
				return nil, err
		}
		if interceptor == nil {
				return srv.(CheckerServer).Check(ctx, in)
		}
		info := &grpc.UnaryServerInfo{
				Server:     srv,
				FullMethod: "/check.Checker/Check",
		}
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
				return srv.(CheckerServer).Check(ctx, req.(*Request))
		}
		return interceptor(ctx, in, info, handler)
}

var _Checker_serviceDesc = grpc.ServiceDesc{
		ServiceName: "check.Checker",
		HandlerType: (*CheckerServer)(nil),
		Methods: []grpc.MethodDesc{
				{
						MethodName: "check",
						Handler:    _Checker_Check_Handler,
				},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "check.proto",
}
